AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  puppter-lambda

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: true

  PuppetterFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 800
      CodeUri: src/
      PackageType: Image
      Events:
        WebsiteCrawl:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST 
            Path: /
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src

Outputs:
  PuppeteerFunctionEndpoint:
    Value:
      Fn::Sub: "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
